USE COMPANY;
SELECT * FROM EMP_INFO;

-- ARITHMETIC OPERATOR
INSERT INTO EMP_INFO(ID,NAME,JDATE,SAL) VALUES
(5, 'John Doe', '2023-01-01', 50000),
(6, 'Jane Smith', '2022-12-15', 55000),
(7, 'Mike Johnson', '2023-02-20', 60000);

-- WRITE SQL QUERY TO DISPLAY 
-- EMPLOYEE NAME,SALALRY AND ANNUAL SALARY OF ALL EMPLOYEES.
SELECT NAME,SAL,SAL*12 FROM EMP_INFO;

-- EMPLOYEE NAME.SALARY AND EACCH DAY SALARY OF ALL EMPLOYEES.
SELECT NAME,SAL,SAL/30 FROM EMP_INFO;

-- EMPLOYEE NAME,SALARY, AND 10% OF THE SALARY AS BONUS.
SELECT NAME,SAL,0.10*SAL FROM EMP_INFO;

-- EMPLOYEE NAME,SALARY, AND 10% OF THE SALARY AS BONUS.(USE BONUS AS TITLE)
SELECT NAME,SAL,0.10*SAL 'SAL WITH 10% BONUS' FROM EMP_INFO;

-- EMPLOYEE NAME,SALARY, AND 5% OF THE SALARY AS TA.
SELECT NAME,SAL,0.05*SAL 'AS TA' FROM EMP_INFO;

-- EMPLOYEE NAME,SALARY AS BASIC SALARY,THEN DISPLAY 3% TA, 6% AS DA, 12% HRA,8% AS COMM,AND FINAL SALARY.
SELECT NAME,SAL 'BASIC SAL' ,0.03*SAL 'TA',0.06*SAL 'DA', 0.12*SAL 'HRA',0.08*SAL 'COMM',(0.03*SAL+0.06*SAL+ 0.12*SAL +0.08*SAL ) AS 'TOTAL' FROM EMP_INFO;


-- RELATIONAL OPERATOR
-- WRITE SQL QUERY TO DISPLAY
-- EMPLOYEE DETAILS HAVING SALARIES LESS THAN 250000
SELECT * FROM EMP_INFO WHERE SAL<25000;

-- EMPLYEE DETAILS HAVING LESS THAN OR EQUAL TO 25000
SELECT * FROM EMP_INFO WHERE SAL<=25000;
-- EMPLOYEE DETAILS HAVING SALARIES EQUAL TO 50000
SELECT * FROM EMP_INFO WHERE SAL=50000;
-- EMPLOYEE DETAILS THOSE ARE NOT GETTING 40000
SELECT * FROM EMP_INFO WHERE NOT SAL<40000;

-- EMPLOYEE DETAILS WHOSE NAME IS PRIYANKA
SELECT * FROM EMP_INFO WHERE NAME="Priyanka";

-- EMPLOYEE DETAILS WHO JOINED ON 22ND OCT 2019.
SELECT * FROM EMP_INFO WHERE JDATE='2019-10-22';


-- LOGICAL OPERATOR
-- THE LOGICAL OPERATOR IS USED TO COMBINE MULTIPLE RELATIONAL STATEMENTS.
-- AND,OR,NOT
# a) Write a SQL query to display employee details those who are getting a salary greater than 25,000 and JDATE is 2019-10-22.
SELECT * FROM EMP_INFO WHERE (SAL>25000 AND JDATE='2019-10-22');
# b) Write a SQL query to display employee details those who are getting a salary of between 30,000 and 50,000.
SELECT * FROM EMP_INFO WHERE (SAL>30000 AND SAL<50000);
# c) Write a SQL query to display employee details those who have joined after December 12th, 2019, or are getting a salary greater than 25,000.
SELECT * FROM EMP_INFO WHERE(JDATE>'2019-12-12' OR SAL>25000);
# d) Write a SQL query to display employee details those who are getting a salary greater than 25,000 and JDATE is AFTER 2022-10-22, or those who are getting a salary greater than 30,000.
SELECT * FROM EMP_INFO WHERE (SAL>25000 AND JDATE>'2019-12-12') OR (SAL>30000);
# e) Write a SQL query to display employee details for those who have not joined on oct 22nd 2022.
SELECT * FROM EMP_INFO WHERE NOT JDATE='2022-09-22' ;


