USE COMPANY;

select * from EMP_INFO;
-- DELETE ALL RECORD FROM TABLE
DELETE FROM EMP_INFO;

-- DELTE EMPLOYEES WITH SALARIES BELOW 40000.
SET SQL_SAFE_UPDATES=0;
DELETE FROM EMP_INFO WHERE SAL<40000;

-- DELETE ALL EPLOYEES WITH SALARIES BETWEEN 40000 AND 60000.
DELETE FROM EMP_INFO WHERE SAL>40000 AND SAL<60000;

-- DELETE THE EMPLOYEE WHOSE NAME IS RAMA.
DELETE FROM EMP_INFO WHERE NAME='RAMA';