USE UNIVERSITY;

#INSERT COMMAND
CREATE TABLE STUDENTS(
 ID INT,
 NAME VARCHAR(20),
 COURSE VARCHAR(20)
);

# APPROACH-1
INSERT INTO STUDENTS(ID,NAME,COURSE) VALUES(1,'PRITI','B.TECH');
INSERT INTO STUDENTS(ID,NAME,COURSE) VALUES(2,'KRITI','M.TECH');
SELECT * FROM STUDENTS;

# APPROACH-2
INSERT INTO STUDENTS VALUES(3,'RAK','B.TECH');
SELECT * FROM STUDENTS;


# APPROACH-3:INSERY MULTIPLE RECORD AT A TIME

INSERT INTO STUDENTS(ID,NAME,COURSE) VALUES
(4,'JACK','AI'),
(5,'SCOT','ML'),
(6,'ROM','MSC');
SELECT * FROM STUDENTS;

# APPROACH-4:INSERY MULTIPLE RECORD AT A TIME
INSERT INTO STUDENTS(ID,NAME,COURSE) VALUES
ROW(7,'SAM','IOT'),
ROW(8,'KAM','SOP'),
ROW(9,'KAM','EE');
SELECT * FROM STUDENTS;