# IS NULL AND IS NOT NULL

USE COMPANY;
CREATE TABLE STAFF(
ID INT,
NAME VARCHAR(20),
EMAIL VARCHAR(20),
ADDRESS VARCHAR(20)
);

INSERT INTO STAFF (ID, NAME, EMAIL, ADDRESS) VALUES
(1, 'John Doe', 'johoe@example.com', '123 Main St'),
(2, 'Jane Smith', 'janeh@example.com', NULL),
(3, 'Emily Davis', NULL, NULL),
(4, 'Michael Brown', 'michan@example.com', '101 Maple St'),
(5, 'Sarah Wilson', NULL, '202 Pine St');

SELECT * FROM STAFF;

# q
-- ALL EMPLOYESS WHOSE EMAIL ID IS NULL.
SELECT * FROM STAFF WHERE EMAIL IS NULL;

-- ALL EMPLOYESS WHOSE EMAIL ID NAD ADDRESS IS NULL.
SELECT * FROM STAFF WHERE EMAIL IS NULL AND ADDRESS IS NULL;

-- ALL EMPLOYESS WHOSE EMAIL ID IS NOT NULL.
SELECT * FROM STAFF WHERE EMAIL IS NOT NULL;