# LIMIT AND OFFSET

USE COM;
SHOW TABLES;
SELECT * FROM EMPLOYEES;

SELECT * FROM EMPLOYEES LIMIT 2;

# IT WILL DISPLAY RECORD PRESENT IN TABLE IF 29 RECORD ARE NOT PRESENT
SELECT * FROM EMPLOYEES LIMIT 29;


SELECT * FROM EMPLOYEES LIMIT 3,3;
# FAST 3 IS 3+1 SO STARTED FROM 4  

SELECT * FROM EMPLOYEES LIMIT 0,3;
SELECT * FROM EMPLOYEES LIMIT 0;

-- LIMIT WITH OFFSET WITH WHERE CLAUSE.
USE COMPANY;
SELECT * FROM STAFF;

SELECT * FROM STAFF WHERE ADDRESS IS NULL LIMIT 1;

SELECT * FROM STAFF WHERE ADDRESS IS NULL LIMIT 1,2;