# RENAME COMMAND 
CREATE DATABASE UNIVERSITY;
USE UNIVERSITY;
CREATE TABLE STUD(
 ID INT,
 NAME VARCHAR(20),
 COURSE VARCHAR(20)
);
DESC STUD;
#RENAME STUD TABLE TO STUDENT
RENAME TABLE STUD TO STUDENT;
DESC STUDENT;
SHOW TABLES;

# RENAME MULTIPLE TABLE AT A TIME
CREATE TABLE BOOKS(
 ID INT,
 NAME VARCHAR(20),
 PRICE INT 
);
CREATE TABLE EMP(
 ID INT,
 NAME VARCHAR(20),
 DEPT VARCHAR(20)
);
SHOW TABLES;
RENAME TABLE BOOKS TO BOOKIES,EMP TO EMPLOYEE;
SHOW TABLES;


#RENAME A TABLE W=USING ALTER WITH RENAME
ALTER TABLE BOOKIES RENAME TO COOKIES;