USE COMPANY;

INSERT INTO EMP_INFO VALUES(4,'SITA','2022-09-22','40000');

-- select all the records from table 
select * from EMP_INFO;

-- select name and salary of all the employee.
SELECT NAME,SAL FROM EMP_INFO;

-- SELECT NAME AND JOINING DATE OF ALL THE EMPLOYESS THOSE WHO JOINED AFTER 2021-08-15.
SELECT NAME,JDATE FROM EMP_INFO WHERE JDATE>'2021-08-1';

-- SELECT ALL THE EMPLOYESS THOSE WHO JOINED AFTER 2020.
SELECT NAME,JDATE FROM EMP_INFO WHERE JDATE>'2020-12-31';

-- SELECT ALL THE EMP NAME AND SAL THOSE WHO ARE GETTING MORE THAN 300000 WITH CHANGING ITS OUTPUT NAME
SELECT NAME,SAL AS ' SAL MORE GHAN 30K' FROM EMP_INFO WHERE SAL>30000;
select 8 from EMP_INFO;
select 2*1 from EMP_INFO;
SELECT NAME FROM EMP_INFO;

-- HOW TO CHANGE THE NAME OF OUTPUT TITLE.
